"""
Phase 2c Shadow Tracker — Live Monitoring & Reporting

Tracks Phase 2c model behavior in live production to answer:
  1. Is RB behaving as backtest predicts? (signal count, acceptance, projected R)
  2. Is PBL continuing to drag? (projected PF, hit rate, opportunity cost)
  3. Are portfolio controls working? (capital cap, position blocking, conflicts)
  4. Is recent behavior closer to OOS or full-period?

Architecture:
  - Singleton `shadow_tracker` instance
  - Called from scanner (signal generation) and paper_executor (outcome tracking)
  - Persists to data/phase2c_shadow_log.jsonl (one record per event)
  - Thread-safe via RLock (scanner runs on background thread)

Records two event types:
  SIGNAL  — generated by scanner, before execution
  OUTCOME — trade closed, recorded by paper_executor

Usage:
    from core.scanning.shadow_tracker import shadow_tracker
    shadow_tracker.record_signal(...)
    shadow_tracker.record_outcome(...)
    summary = shadow_tracker.get_summary()
"""
from __future__ import annotations

import json
import logging
import os
import threading
import time
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

_DATA_DIR = Path(__file__).resolve().parents[2] / "data"
_LOG_FILE = _DATA_DIR / "phase2c_shadow_log.jsonl"


class Phase2cShadowTracker:
    """Thread-safe tracker for Phase 2c live shadow monitoring."""

    def __init__(self, log_path: Path = _LOG_FILE):
        self._lock = threading.RLock()
        self._log_path = log_path
        self._log_path.parent.mkdir(parents=True, exist_ok=True)

        # In-memory accumulators (loaded from JSONL on init)
        self._signals: list[dict] = []
        self._outcomes: list[dict] = []
        self._load_existing()

    # ── Persistence ──────────────────────────────────────────────────────

    def _load_existing(self):
        """Load existing records from JSONL on startup."""
        if not self._log_path.exists():
            return
        try:
            with open(self._log_path, "r") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        rec = json.loads(line)
                        if rec.get("event_type") == "signal":
                            self._signals.append(rec)
                        elif rec.get("event_type") == "outcome":
                            self._outcomes.append(rec)
                    except json.JSONDecodeError:
                        continue
            logger.info(
                "Phase2cShadowTracker: loaded %d signals + %d outcomes from %s",
                len(self._signals), len(self._outcomes), self._log_path.name,
            )
        except Exception as exc:
            logger.warning("Phase2cShadowTracker: failed to load existing log: %s", exc)

    def _append_record(self, record: dict):
        """Append a single JSON record to the JSONL log."""
        try:
            with open(self._log_path, "a") as f:
                f.write(json.dumps(record, default=str) + "\n")
        except Exception as exc:
            logger.warning("Phase2cShadowTracker: write error: %s", exc)

    # ── Signal Recording (called from scanner) ───────────────────────────

    def record_signal(
        self,
        symbol: str,
        model: str,
        direction: str,
        strength: float,
        entry_price: float,
        stop_loss: float,
        take_profit: float,
        regime: str,
        was_boosted: bool = False,
        was_relaxed: bool = False,
        breakout_active: bool = False,
        rb_confidence: float = 0.0,
        rb_range_width: float = 0.0,
        passed_confluence: bool = False,
        passed_risk_gate: bool = False,
        was_executed: bool = False,
        rejection_reason: str = "",
        rb_cap_applied: bool = False,
        rb_pos_blocked: bool = False,
        position_size_usdt: float = 0.0,
        rationale: str = "",
    ):
        """Record a Phase 2c signal event."""
        with self._lock:
            # Compute projected R:R
            risk = abs(entry_price - stop_loss) if entry_price and stop_loss else 0
            reward = abs(take_profit - entry_price) if take_profit and entry_price else 0
            projected_rr = round(reward / risk, 4) if risk > 0 else 0.0

            record = {
                "event_type": "signal",
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "symbol": symbol,
                "model": model,
                "direction": direction,
                "strength": round(strength, 4),
                "entry_price": round(entry_price, 4) if entry_price else 0,
                "stop_loss": round(stop_loss, 4) if stop_loss else 0,
                "take_profit": round(take_profit, 4) if take_profit else 0,
                "projected_rr": projected_rr,
                "regime": regime,
                "was_boosted": was_boosted,
                "was_relaxed": was_relaxed,
                "breakout_active": breakout_active,
                "rb_confidence": round(rb_confidence, 4),
                "rb_range_width": round(rb_range_width, 4),
                "passed_confluence": passed_confluence,
                "passed_risk_gate": passed_risk_gate,
                "was_executed": was_executed,
                "rejection_reason": rejection_reason,
                "rb_cap_applied": rb_cap_applied,
                "rb_pos_blocked": rb_pos_blocked,
                "position_size_usdt": round(position_size_usdt, 2),
                "rationale": rationale[:200] if rationale else "",
            }

            self._signals.append(record)
            self._append_record(record)

            logger.info(
                "Phase2c SIGNAL: %s %s %s str=%.3f RR=%.2f exec=%s%s%s",
                model, symbol, direction, strength, projected_rr,
                "YES" if was_executed else "NO",
                f" [{rejection_reason}]" if rejection_reason else "",
                " [BOOSTED]" if was_boosted else "",
            )

    # ── Outcome Recording (called from paper_executor) ───────────────────

    def record_outcome(
        self,
        symbol: str,
        model: str,
        direction: str,
        entry_price: float,
        exit_price: float,
        stop_loss: float,
        take_profit: float,
        pnl_usdt: float,
        r_value: float,
        exit_reason: str,
        duration_s: float,
        size_usdt: float,
        was_boosted: bool = False,
        was_relaxed: bool = False,
    ):
        """Record a Phase 2c trade outcome."""
        with self._lock:
            record = {
                "event_type": "outcome",
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "symbol": symbol,
                "model": model,
                "direction": direction,
                "entry_price": round(entry_price, 4),
                "exit_price": round(exit_price, 4),
                "stop_loss": round(stop_loss, 4),
                "take_profit": round(take_profit, 4),
                "pnl_usdt": round(pnl_usdt, 4),
                "r_value": round(r_value, 4),
                "exit_reason": exit_reason,
                "duration_s": round(duration_s, 1),
                "size_usdt": round(size_usdt, 2),
                "was_boosted": was_boosted,
                "was_relaxed": was_relaxed,
            }

            self._outcomes.append(record)
            self._append_record(record)

            logger.info(
                "Phase2c OUTCOME: %s %s %s PnL=$%.2f R=%.3f exit=%s%s",
                model, symbol, direction, pnl_usdt, r_value, exit_reason,
                " [BOOSTED]" if was_boosted else "",
            )

    # ── Summary / Reporting ──────────────────────────────────────────────

    def get_summary(self, last_n_hours: Optional[float] = None) -> dict:
        """
        Compute a shadow summary over the full log or last N hours.
        Returns the structured report matching Phase 3b requirements.
        """
        with self._lock:
            signals = list(self._signals)
            outcomes = list(self._outcomes)

        if last_n_hours is not None:
            cutoff = datetime.now(timezone.utc).timestamp() - (last_n_hours * 3600)
            signals = [
                s for s in signals
                if _parse_ts(s.get("timestamp", "")) >= cutoff
            ]
            outcomes = [
                o for o in outcomes
                if _parse_ts(o.get("timestamp", "")) >= cutoff
            ]

        # ── 1. Signal Distribution ───────────────────────────────────
        signal_dist = defaultdict(lambda: {"total": 0, "executed": 0, "blocked": 0, "by_dir": defaultdict(int)})
        for s in signals:
            m = s["model"]
            signal_dist[m]["total"] += 1
            if s.get("was_executed"):
                signal_dist[m]["executed"] += 1
            else:
                signal_dist[m]["blocked"] += 1
            signal_dist[m]["by_dir"][s.get("direction", "unknown")] += 1

        # ── 2. Model Contribution (from outcomes) ────────────────────
        model_contrib = {}
        for model_name in ("pullback_long", "swing_low_continuation", "range_breakout"):
            m_outcomes = [o for o in outcomes if o["model"] == model_name]
            n = len(m_outcomes)
            if n == 0:
                model_contrib[model_name] = {
                    "n": 0, "wr": 0, "pf": 0, "avg_r": 0,
                    "total_pnl": 0, "sl_rate": 0,
                }
                continue
            wins = [o for o in m_outcomes if o["pnl_usdt"] > 0]
            gross_profit = sum(o["pnl_usdt"] for o in wins)
            gross_loss = abs(sum(o["pnl_usdt"] for o in m_outcomes if o["pnl_usdt"] <= 0))
            sl_hits = [o for o in m_outcomes if o["exit_reason"] == "sl"]
            model_contrib[model_name] = {
                "n": n,
                "wr": round(len(wins) / n, 4) if n else 0,
                "pf": round(gross_profit / gross_loss, 4) if gross_loss > 0 else 999.0,
                "avg_r": round(sum(o["r_value"] for o in m_outcomes) / n, 4) if n else 0,
                "total_pnl": round(sum(o["pnl_usdt"] for o in m_outcomes), 2),
                "sl_rate": round(len(sl_hits) / n, 4) if n else 0,
            }

        # ── 3. Portfolio Controls ────────────────────────────────────
        rb_signals = [s for s in signals if s["model"] == "range_breakout"]
        controls = {
            "rb_cap_applied": sum(1 for s in rb_signals if s.get("rb_cap_applied")),
            "rb_pos_blocked": sum(1 for s in rb_signals if s.get("rb_pos_blocked")),
            "rb_executed": sum(1 for s in rb_signals if s.get("was_executed")),
            "rb_total_signals": len(rb_signals),
            "rb_avg_projected_rr": round(
                sum(s.get("projected_rr", 0) for s in rb_signals) / len(rb_signals), 4
            ) if rb_signals else 0,
        }

        # Enhancement stats
        pbl_signals = [s for s in signals if s["model"] == "pullback_long"]
        enhancement = {
            "n_boosted": sum(1 for s in pbl_signals if s.get("was_boosted")),
            "n_relaxed": sum(1 for s in pbl_signals if s.get("was_relaxed")),
            "anti_amplification": sum(
                1 for s in pbl_signals if s.get("breakout_active")
            ),
        }

        # Conflict tracking (signals on same bar/symbol)
        conflict_map = defaultdict(list)
        for s in signals:
            key = (s.get("timestamp", "")[:16], s.get("symbol"))  # minute-level grouping
            conflict_map[key].append(s["model"])
        conflicts = {
            "pbl_rb_same_bar": sum(
                1 for models in conflict_map.values()
                if "pullback_long" in models and "range_breakout" in models
            ),
            "slc_rb_same_bar": sum(
                1 for models in conflict_map.values()
                if "swing_low_continuation" in models and "range_breakout" in models
            ),
        }

        # ── 4. Rolling PF ───────────────────────────────────────────
        all_outcomes_sorted = sorted(outcomes, key=lambda o: o.get("timestamp", ""))
        rolling_pf_20 = _compute_rolling_pf(all_outcomes_sorted, 20)
        rolling_pf_50 = _compute_rolling_pf(all_outcomes_sorted, 50)

        # ── 5. Combined KPIs ─────────────────────────────────────────
        total_n = len(outcomes)
        total_wins = [o for o in outcomes if o["pnl_usdt"] > 0]
        total_gp = sum(o["pnl_usdt"] for o in total_wins)
        total_gl = abs(sum(o["pnl_usdt"] for o in outcomes if o["pnl_usdt"] <= 0))

        combined = {
            "n": total_n,
            "wr": round(len(total_wins) / total_n, 4) if total_n else 0,
            "pf": round(total_gp / total_gl, 4) if total_gl > 0 else 999.0,
            "avg_r": round(
                sum(o["r_value"] for o in outcomes) / total_n, 4
            ) if total_n else 0,
            "total_pnl": round(sum(o["pnl_usdt"] for o in outcomes), 2),
        }

        # ── Per-asset breakdown ──────────────────────────────────────
        per_asset = {}
        symbols_seen = set(o["symbol"] for o in outcomes)
        for sym in symbols_seen:
            sym_out = [o for o in outcomes if o["symbol"] == sym]
            n = len(sym_out)
            w = [o for o in sym_out if o["pnl_usdt"] > 0]
            gp = sum(o["pnl_usdt"] for o in w)
            gl = abs(sum(o["pnl_usdt"] for o in sym_out if o["pnl_usdt"] <= 0))
            per_asset[sym] = {
                "n": n,
                "wr": round(len(w) / n, 4) if n else 0,
                "pf": round(gp / gl, 4) if gl > 0 else 999.0,
                "pnl": round(sum(o["pnl_usdt"] for o in sym_out), 2),
                "pbl_n": len([o for o in sym_out if o["model"] == "pullback_long"]),
                "slc_n": len([o for o in sym_out if o["model"] == "swing_low_continuation"]),
                "rb_n": len([o for o in sym_out if o["model"] == "range_breakout"]),
            }

        return {
            "period": {
                "last_n_hours": last_n_hours,
                "n_signals": len(signals),
                "n_outcomes": len(outcomes),
                "generated_at": datetime.now(timezone.utc).isoformat(),
            },
            "combined": combined,
            "signal_distribution": {k: dict(v) for k, v in signal_dist.items()},
            "model_contribution": model_contrib,
            "controls": controls,
            "enhancement": enhancement,
            "conflicts": conflicts,
            "rolling_pf": {
                "rpf_20": rolling_pf_20,
                "rpf_50": rolling_pf_50,
            },
            "per_asset": per_asset,
        }

    def get_signal_count(self) -> dict:
        """Quick signal count summary for dashboard display."""
        with self._lock:
            counts = defaultdict(int)
            for s in self._signals:
                counts[s["model"]] += 1
            return dict(counts)

    def get_outcome_count(self) -> dict:
        """Quick outcome count summary for dashboard display."""
        with self._lock:
            counts = defaultdict(int)
            for o in self._outcomes:
                counts[o["model"]] += 1
            return dict(counts)


def _parse_ts(ts_str: str) -> float:
    """Parse ISO timestamp string to epoch seconds."""
    try:
        dt = datetime.fromisoformat(ts_str)
        return dt.timestamp()
    except Exception:
        logging.getLogger(__name__).warning("_parse_ts: invalid timestamp %r, defaulting to 0.0", ts_str)
        return 0.0


def _compute_rolling_pf(outcomes: list[dict], window: int) -> Optional[float]:
    """Compute rolling PF over last N outcomes."""
    if len(outcomes) < window:
        return None
    window_trades = outcomes[-window:]
    gp = sum(o["pnl_usdt"] for o in window_trades if o["pnl_usdt"] > 0)
    gl = abs(sum(o["pnl_usdt"] for o in window_trades if o["pnl_usdt"] <= 0))
    return round(gp / gl, 4) if gl > 0 else 999.0


# ── Module-level singleton ───────────────────────────────────────────────
shadow_tracker = Phase2cShadowTracker()
